[3055] prevent from passing different cx and getValue functions to children components when the results of those functions remain the same as previous render.
JedWatson/react-select pull request #4084
Opened 2020-06-11 18:30 UTC by manvydasu

During the render of Select component, functions cx and getValue are recreated as new functions everytime and are passed to children components. Sometimes the result of cx and getValue is same as previous render, but the functions are still re-created thus causing unnecessary re-renders as result. The issue was originally described here: https://github.com/JedWatson/react-select/issues/3055

Would love if someone could suggest a cleaner way to fix this.

2020-06-11 23:43 UTC, Rall3n commented
I think a better/cleaner solution for both would be to create the functions on class level and just add them to the `commonProps` object.

```jsx
getValue = () => this.state.selectValue;

cx = (...args) => classNames(this.props.classNamePrefix, ...args);

/* ... */
getCommonProps() {
    const { /* ... */ cx, getValue, props } = this;

    /* ... */

    return {
        cx,
        getValue,
        /* ... */
    };
}
```

No need for memoization and no need for "creation"-functions.

2020-06-12 17:09 UTC, manvydasu commented
@Rall3n 
Yeah, you're right. I over engineered that originally. Updated just as you suggested.

2020-06-24 05:32 UTC, bladey commented
Look good to me, @JedWatson to review.

2020-11-18 15:08 UTC, Methuselah96 requested changes

2020-11-18 15:08 UTC, Methuselah96 commented on packages/react-select/src/Select.js
> +  cx = (...args: any) => classNames(this.props.classNamePrefix, ...args);
```suggestion
  cx = (...args: Array<any>) => classNames(this.props.classNamePrefix, ...args);
```

2020-12-11 02:43 UTC, JedWatson approved these changes

2020-12-11 02:54 UTC, JedWatson commented
Thanks @manvydasu

2020-12-11 02:54 UTC, merged