Support for required attribute
JedWatson/react-select pull request #4140
Opened 2020-07-26 19:14 UTC by natanaelsimoes

Required prop added to base Select and also to Input component.

At Input, a regular HTML Input was created just to handle the required as the AutosizeInput does not handle it (don't know why). The selected value is sent to that hidden input, if any.

Now native HTML validation works!

2020-07-26 21:19 UTC, Rall3n commented
Making the `Select` component not searchable (setting `isSearchable` to false) will remove the `Input` component and the underlying (new) `<input>` element handling the `required` attribute.

2020-08-27 11:19 UTC, chocobuckle commented
Any update on this folks? Support for the 'required' attribute is quite a dealbreaker!

2020-09-06 13:11 UTC, irfanalef2060 commented
@chocobuckle  same here dude. For now, I am thinking to write a wrapper component to support the required functionality.

2020-11-14 16:25 UTC, Methuselah96 commented
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this PR on the fork and we can get it merged and released.

2020-11-20 08:00 UTC, willymwai commented
Actually there's a way to enable the required attribute

`import Select, {components} from "react-select";`

`const Input = props => {`
               ` if (props.isHidden) {`
                    `return <components.Input {...props} required={true}/>;`
                `}`
                `return (`
                        `<components.Input {...props} required={true}/>`
                `);`
           ` };`

<Select components={{Input}}
/>

2020-12-08 08:40 UTC, dolie commented
I need it !

2020-12-08 09:11 UTC, kylemh commented on packages/react-select/src/components/Input.js
> +  required ?: boolean,
```suggestion
  form?: string,
  /** Checks if the input has some value */
  required?: boolean,
```

2020-12-09 23:20 UTC, ebonow requested changes

2020-12-09 23:20 UTC, ebonow commented on packages/react-select/src/Select.js
> +        value={value ? value.value : inputValue}
This would be a breaking change as existing behavior is to clear the input onBlur.

2021-01-21 00:40 UTC, ebonow commented
Greetings @nathsimpson and my apologies for such a long wait until receiving a response to this PR.

I wanted to thank you for the effort and time you put into making this for the community. It seems unacceptable that so much time had passed from your time of development to a response about having it reviewed. I apologize that this was the case and our contributor community deserves to know that they are heard and trying to contribute to a mutual cause.

Myself, the team and the community appreciate any and all efforts to improve react-select.

That said, I wanted to inform you that this PR will be closed for the following reasons:
1) Introduces breaking behavior in regards to how blurring the input is handled.
2) Does not cover the use-case for when isSearchable is false isMulti is true.

Regarding the first point, I agree that it is less than ideal to create a controlled input simply to add required validation and we  agree that validation is important. I have created issue https://github.com/JedWatson/react-select/issues/4327 to discuss the complexities and possible approaches to support it for all possible combinations that is allowed by the Select.

Should you be able to implement the behavior without breaking changes, a more complete implementation to cover all variations of Select, and add unit tests to ensure there are all covered, we can of course revisit this and re-open the PR.

Again thank you for the contribution.

2021-01-21 00:40 UTC, closed without merging