Declare event listeners as non-passive to remove browser warnings
JedWatson/react-select pull request #4437
Opened 2021-02-08 16:16 UTC by ebonow

### Problem:
Chrome issues console warnings when adding some event listeners without declaring them as passive. Three of these warnings present themselves in a non-mobile view when opening the menu.

<img width="1080" alt="Screen Shot 2021-02-08 at 8 13 03 AM" src="https://user-images.githubusercontent.com/1007579/107246843-87b2c780-69e5-11eb-9226-6a8e5da41ae9.png">

### Resolution:
By explicitly setting passive is false, Chrome will no longer show this warning in the console.

2021-02-09 11:30 UTC, JedWatson requested changes
I took a look and there is a backwards compatibility concern here with older browsers -- https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection

Off the top of my head I'm **not confident** that this wouldn't cause a problem for browsers that react-select supports **in the wild**, so unless we wait for a major release, I'd be more comfortable if we added the compatibility check in here.

(note: with the next major version we should really clarify our browser support so stuff like this doesn't come up again! I think evergreen is fair these days, and IE is dead, but when we rewrote for v2 IE11 was still actually a target for Atlassian so unless someone knows other reasons it wouldn't still work on IE, it may, and if so people using it may also be relying on that 🤷‍♂️)

2021-02-09 15:11 UTC, ebonow commented
@JedWatson Thanks for the heads up on that and I did miss that consideration, though I did see this was something that had been explored before.

This may be a case where we'd like to include the polyfill and consider removing it for some major release. I understand the warnings are fairly innocuous, but ultimately it reflects poorly on on the devs using react-select to have Chrome console spamming 3 warning messages every time a menu is opened.

2021-02-10 00:18 UTC, ebonow commented
@JedWatson , I added a polyfill to support legacy browsers. 

Also in regards to this line...
https://github.com/JedWatson/react-select/blob/9aaf35b0c41b8c89da42430365c8c58cc3b41815/packages/react-select/src/internal/useScrollCapture.js#L106

I know I am fairly new to Flow, but the events are being attached directly to the DOM, so wouldn't they be actual Wheel/Touch events and not synthetic events?

2021-03-04 22:36 UTC, JedWatson approved these changes

2021-03-04 22:37 UTC, merged