Single value layout fix
JedWatson/react-select pull request #4720
Opened 2021-08-13 04:10 UTC by seancurtis

The absolute positioning pulls both the value and the placeholder out of the flow, and thus the component itself collapses down when used as a flex child. This can be solved by wrapping the component in another div, but we can solve it better by using CSS Grid instead.

<img width="593" alt="before-after" src="https://user-images.githubusercontent.com/157960/129303649-73afd0dc-5d11-4c7d-b39b-42fa18c1b1f9.png">

2021-08-15 14:48 UTC, Rall3n commented on packages/react-select/src/components/containers.tsx
> +  display: `${isMulti ? 'flex' : 'grid'}`,
Question of style, not critical, but why literals when you can do it without them?

2021-08-15 14:50 UTC, Rall3n requested changes
![image](https://user-images.githubusercontent.com/15950630/129482464-f4610a83-6170-440a-b623-2384da04a0a3.png)

Value, placeholder and input are centered by default instead of left aligned.

2021-08-30 06:47 UTC, seancurtis commented
@Rall3n thanks for the catch in the layout when expanded. I was working on it using a fixture to test the flex content and as such it was constantly squashed. I just reverted it before pushing. I did some more fixes to the layout/alignment as I noticed another issue too. It's much more solid now.

2021-08-30 07:03 UTC, Rall3n requested changes
One last thing, but everything else looks ok.

2021-08-30 07:03 UTC, Rall3n commented on packages/react-select/src/components/Placeholder.tsx
> +  gridArea: '1 / 2',
![image](https://user-images.githubusercontent.com/15950630/131299022-3d7e066a-8950-4b4b-a44e-e30a1e694fa2.png)

Forgot to provide the `Placehholder` component with the latest fix :)

2021-08-30 23:48 UTC, seancurtis commented
D'oh! Not sure how I missed that one tbh. Should be good now.

2021-08-31 08:09 UTC, Rall3n approved these changes
Looks good now 👍

2021-09-02 23:43 UTC, Methuselah96 commented on packages/react-select/src/components/containers.tsx
> +  isMulti
To make Prettier happy:
```suggestion
  isMulti,
```

2021-09-02 23:59 UTC, JedWatson approved these changes
Nice! Ha, love css grids, this is so neat now. Thanks @seancurtis

2021-09-03 00:04 UTC, merged