Remove duplicate handler for indicator
JedWatson/react-select pull request #5085
Opened 2022-02-28 19:15 UTC by rkulinski

2022-03-01 09:48 UTC, Rall3n requested changes
Removing the dedicated event handler for the `DropdownIndicator` component introduces breaking changes and also breaks interaction with the component when using the prop `openMenuOnClick`:
* setting `openMenuOnClick={false}` does not open the menu when clicking on the indicator
* additionally setting `isSearchable={false}` shows no indication of interaction with the component upon clicking the indicator (resembles an `<select readonly />` element)

Even though both handlers do the same actions, they react in different ways to the interaction. One should not be removed on the basis that they both end in the same behavior. Instead, a way should be found to replace `stopPropogation` without changing current behaviour.

2022-03-01 10:39 UTC, rkulinski commented
@Rall3n got it, I wasn't able to find any difference in how it was working, but I'm not that familiar with library code so I missed some edge case scenarios. I'll try to somehow get rid of `stopPropagation`, but I'm not sure if this will be easy.

2022-03-01 15:03 UTC, rkulinski commented
@Rall3n I wasn't able to find any better and easier workaround for this with how components are structured.

2022-03-02 10:31 UTC, rkulinski commented
Closing in favor of https://github.com/JedWatson/react-select/pull/5089

2022-03-02 10:31 UTC, closed without merging